name: Daily Landscape Graph Population
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://landscape.cncf.io/data/items.json
          downloaded_filename: landscape-items.json
      - name: Neo4j import landscape data from json
        uses: johnymontana/flat-graph@v1.1
        with:
          neo4j-user: ${{secrets.NEO4J_USER}}
          neo4j-password: ${{secrets.NEO4J_PASSWORD}}
          neo4j-uri: ${{secrets.NEO4J_URI}}
          filename: landscape-items.json
          cypher-query: >
            CREATE CONSTRAINT const_Card IF NOT EXISTS 
            FOR (n:Card) REQUIRE n.name IS UNIQUE 
            
            CREATE CONSTRAINT const_Industry IF NOT EXISTS
            FOR (n:Industry) REQUIRE n.name IS UNIQUE 
            
            CREATE CONSTRAINT const_Repo IF NOT EXISTS 
            FOR (n:Repo) REQUIRE n.name IS UNIQUE

            UNWIND $value AS item MERGE (c:Card {name: item.name}) 
            SET
              c += item { 
                .bestPracticeBadgeId, 
                .bestPracticePercentage, 
                .commitsThisYear, 
                .contributorsCount, 
                .crunchbase, 
                .description, 
                .homepage_url, 
                .isSubsidiaryProject, 
                .logo,
                .member, 
                .name,      // i
                .oss,       // i
                .repo_url, 
                .stars, 
                .twitter,
              }

            WITH c, item
  
            FOREACH (industry in item.industries |
              MERGE (i:Industry {name: industry})
              MERGE (c)-[:IN_INDUSTRY]->(i)
            )

            FOREACH (language in item.github_data.languages |
              MERGE (l:Language {name: language.name})
              MERGE (c)-[:USES_LANGUAGE]->(l)
            )

            FOREACH (repo IN item.repos |
              MERGE (r:Repo {name: repo.url}) // TODO: should parse out an org/repo id for this
              MERGE (c)-[:OWNS_REPO]->(r)
            )
